[project]
name = "instacertify"
authors = [
    { name = "InstaCertify", email = "nikhil@instacertify.com"}
]
description = "InstaCertify Consulting ERP — certification & testing on ERPNext 16.32.3"
requires-python = ">=3.14"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "PyQRCode~=1.2.1",
    "pypng~=0.20220715.0",
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.dev-dependencies]
